sudo: required

dist: xenial

language: python
python:
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1


stages:
  - name: test
    if: type = push
  - name: build
    if: branch = develop AND type = push
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      before_install:
        - make travis-infra
        - export PATH="~/bin:$PATH"
      install: make travis-env
      services:
        - docker
      script:
        - make test
        - make code-style
      after_success:
        - codecov

    - stage: build
      before_install:
        - make travis-infra
        - export PATH="~/bin:$PATH"
      install: make travis-env
      services:
        - docker
      script:
        - make app-docker-build
        - make thumbnail-lambda
        - make rekognition-lambda

    - stage: deploy
      before_install:
        - make travis-infra
        - export PATH="~/bin:$PATH"
      install: make travis-env
      services:
        - docker
      script:
        - make aws-push-image
        - make thumbnail-lambda
        - make rekognition-lambda
        - make aws-update-service
        - make aws-update-lambda
